### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/output/haplodmf/haplodmf_matrix.pickle'

### ISSUE THREAD

**Issue by janeshen91** [dhcai21/HaploDMF#5]
Hi

Thank you for creating this tool. I've been trying to use this with some nanopore gridion data. It keeps getting stuck on the following lines

haplodmf.sh: line 497:    57 Killed                  python ./src/fre_matrix.py $file_bam_sorted $file_snv $file_prefix $cond_pro $smallest_snv $num_read_1 $num_read_2 $gap $fre_snv $thread
 $input_snv
Traceback (most recent call last):
  File "./src/dmf.py", line 78, in <module>
    f = open(train_path,'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/output/haplodmf/haplodmf_matrix.pickle'
Traceback (most recent call last):
  File "./src/out_haplotypes.py", line 51, in <module>
    f = open(file_clusters,'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/output/haplodmf/haplodmf_clusters.pickle'
Traceback (most recent call last):
  File "./src/extract_reads.py", line 20, in <module>
    for seq in SeqIO.parse(file,'fasta'):
  File "/opt/conda/envs/test/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/opt/conda/envs/test/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/opt/conda/envs/test/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 48, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/output/haplodmf/haplodmf_consensus.fasta'
Traceback (most recent call last):
  File "./src/run_medaka.py", line 17, in <module>
    for seq in SeqIO.parse(file,'fasta'):
  File "/opt/conda/envs/test/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/opt/conda/envs/test/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/opt/conda/envs/test/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 48, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/output/haplodmf/haplodmf_consensus.fasta'
rm: cannot remove '/output/haplodmf/haplodmf_matrix.pickle': No such file or directory
rm: cannot remove '/output/haplodmf/haplodmf_clusters.pickle': No such file or directory

ERROR conda.cli.main_run:execute(124): `conda run /bin/bash -c -c bash haplodmf.sh -i /output//medaka/barcode01/calls_to_ref.sam -r /output/reference/rED150.fa -o /output/haplodmf` failed. (See above for error)

Can you help please? It looks like it's expecting a pickle file but that pickle file isn't there?

Thanks
Jane

**Comment by dhcai21** [comment]
Hi,

The missing file was created by HaploDMF during processing. It appears that HaploDMF is not working correctly in some steps, but I don't have any clue about the reported error. Please apply HaploDMF to the provided test file to see if it works well.

Also, I noticed that the input file path you provided has two slashes: "/output//medaka/barcode01/calls_to_ref.sam". Perhaps it should be "/output/medaka/barcode01/calls_to_ref.sam"? I believe this may have caused the error.

Feel free to email me if you still have any problems with the running.

Dehan

**Comment by janeshen91** [comment]
Hi Dehan

thanks for the review. I did try removing the extra slash but it produced the same result. I also tried running the test files and it seems to be running fine: that is it's still running and it hasn't produced any errors, and I can see the pickle file being produced in the specified output file. Do you know what would cause the pickle file to not be produced? Is it something in the way that my data is aligned? Do you assume a certain kind of alignment program has been used to align it? Do you require secondary aligments?

I did try to align it using minimap using the same parameters that I used in the test run: ie
docker run -v /vaxart-batch-output/$str:/output \
620901718958.dkr.ecr.us-east-2.amazonaws.com/nanopanel2 minimap2 \
-t 4 -ax map-ont \
/output/reference/rED150.fa \
/output/barcode01/barcode01.fastq -o /output/minimap/barcode01.sam

And then reran with this new alignment file but it didn't work

**Comment by dhcai21** [comment]
Can you send me the data?  I will test it. My email is dhcai2-c@my.cityu.edu.hk

Dehan
